config/routes.rb
Rails.application.routes.draw do

	root 'items#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users

  resources :items do
    resources :join_table_cart_items
  end

  resources :carts, param: :permalink
  # match 'my_cart', to: 'carts#show', via: [:get]
  resources :orders
  resources :charges, only: [:new, :create]

  namespace :admin do
    resources :items
    resources :admins, only: [:index]
    root 'admins#index'
  end

  # get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
	# VALIDATES
	validates :title, presence: true
	validates :description, presence: true, length: { in: 5..100 }
	validates :price, presence: true, numericality: { greater_than: 0 }
	validates :image, presence: true

	has_many :join_table_cart_items
	has_many :carts, through: :join_table_cart_items

	has_many :order_items
	has_many :orders, through: :order_items

	has_one_attached :image

	belongs_to :category
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :is_admin?

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    if params[:item][:image].present?
      @item = Item.new(item_params)
      @item.image_url = url_for(@item.image)
      @item.image.attach(params[:item][:image])
      if @item.save
        redirect_to admin_item_path(@item.id)
      else
        render :new
      end
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path, notice: "L'item a bien été supprimé."
  end


  private
  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :description, :price, :image, :category_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :is_admin?, only: [:destroy, :update, :edit]


  def index
    @items = Item.all
  end

 
  def show
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url)
    end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
	def is_kitty?(item)
		if item.category == Category.first
			true
		else
			false
		end
	end

	def is_kibble?(item)
		if item.category == Category.last
			true
		else
			false
		end
	end
end

app/views/admin/items/edit.html.erb
<div class="content row justify-content-md-center">
  <div class="card col-lg-6 my-5">
    <div class="card-body">
        <h1 class="mb-5">Modifier un item</h1>

        <%= form_for([:admin, @item], :html => {:class => 'input-color'}) do |f| %>
                <%= f.label 'Choisis ton image :' %>
                <%= f.file_field :image, class: 'form-control-file mb-4', :accept => 'image/png,image/gif,image/jpeg', placeholder: @item.image_url %>
                <%= f.text_field :title, class:"form-control mb-4", placeholder: @item.title %>
                <%= f.text_area :description, class:"form-control mb-4", placeholder: @item.description %>
                <%= f.text_field :price, class:"form-control mb-4", placeholder: @item.price %>
                
                <%= f.radio_button :category_id, 1 %>
                <%= f.label :kitty, 'Kitty' %><br/>
               
                <%= f.radio_button :category_id, 2 %>
                <%= f.label :kibble, 'Kibble' %><br/>

                <%= f.submit "Modifier mon item", class: "btn btn-secondary" %>

        <% end %>

    </div>
</div>

app/views/admin/items/index.html.erb
<div class="ecommerce-page">
    <div class="wrapper">
        <div class="main">
            <div class="section" id='img-ancre'>
                <div class="container">
                    <h2 class="section-title">Toutes nos images disponibles</h2>
                        <div class="col-md-12">
                            <div class="row">
                              <% @items.each do |item| %>
                                <div class="col-lg-4 col-md-6">
                                    <div class="card-index">
                                        <div>
                                            <%= link_to admin_item_path(item.id) do %>
                                                <%= image_tag(item.image) if item.image.attached? %>
                                            <% end %>
                                        </div>
                                        <div class="card-body">
                                            <h4 class="title-card"><%= item.title %></h4>
                                            <p class="description-card">
                                                <%= item.description %>
                                            </p>                                       
                                            <div class="price-container">
                                                <span class="price"> &euro; <%= item.price %></span>
                                            </div> 
                                        </div>
                                    </div>
                                </div>
                              <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin/items/new.html.erb
<div class="content row justify-content-md-center">
  <div class="card col-lg-6 my-5">
    <div class="card-body">
        <h1 class="mb-5">Ajouter un item</h1>

        <%= form_for([:admin, @item], :html => {:class => 'input-color'}) do |f| %>
                <%= f.label 'Choisis ton image :' %>
                <%= f.file_field :image, class: 'form-control-file mb-4', :accept => 'image/jpg', :required => true %>
                <%= f.text_field :title, class:"form-control mb-4", placeholder: 'Titre' %>
                <%= f.text_area :description, class:"form-control mb-4", placeholder: 'Description' %>
                <%= f.text_field :price, class:"form-control mb-4", placeholder: 'Prix' %>
                
                <%= f.radio_button :category_id, 1, :checked => true %>
                <%= f.label :kitty, 'Kitty' %><br/>
               
                <%= f.radio_button :category_id, 2 %>
                <%= f.label :kibble, 'Kibble' %><br/>

                <%= f.submit "Ajouter mon item", class: "btn btn-secondary" %>

        <% end %>

    </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">

  <div class="row">
  	<div class="col mt-2">
  		<h2 class="title"><%= @item.title %></h2>
			<p id="notice"><%= notice %></p>
  	</div>
  </div>
	
	<div class="row mb-3">
		<div class="col-md-5 mr-auto">
	  	 	<%= image_tag(@item.image) if @item.image.attached? %>
		</div>

		<div class="col-md-7 btn-color">
			<h5 class="category">Description</h5>
			<p><%= @item.description %></p><br/><br/><br/><br/><br/><br/><br/><br/><br/>
			<%= link_to edit_admin_item_path(@item.id), class: "btn btn-secondary rounded float-left mx-2", method: :get, title: 'Edit the comment' do %>
                <i class="fas fa-pencil-alt"></i>
            <% end %>
			<%= link_to admin_item_path(@item.id), method: "delete", class: "btn btn-danger rounded float-left mx-2", title: 'Delete the gossip', data: { confirm: "Tu es sûr-e de voiloir supprimer cet item ?"} do %>
				<i class="fas fa-trash-alt"></i>
			<% end %>
		</div>
	</div>
	
	<div class="row align-items-center ">


		<div class="col-md-2 ml-auto text-center">
			<span class="title"><%= @item.price %> €</span>
		</div>

	</div>

	<div class="row mt-5">
		<div class="col-md text-right">
			<%= link_to 'Back', items_path %>
		</div>
	</div>

</div>