config/routes.rb
Rails.application.routes.draw do

	root 'items#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users

  resources :items do
    resources :join_table_cart_items
  end

  resources :carts, param: :permalink
  # match 'my_cart', to: 'carts#show', via: [:get]
  resources :orders
  resources :charges, only: [:new, :create]

  namespace :admin do
    resources :items
    resources :admins, only: [:index]
    root 'admins#index'
  end

  # get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	
	has_many :join_table_cart_items
	has_many :items, through: :join_table_cart_items
	#has_many :good_orders

	def to_param
		permalink
	end

  def permalink
  	"my_cart"
	end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :authenticate_user!, only: [:show]

	def show
		@cart = @current_cart
		@sum = sum(@cart)
		@items = Item.all
	end

	def destroy
		@cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
	end

end

app/helpers/carts_helper.rb
module CartsHelper
	def sum(cart)
		sum = 0
		cart.items.each do |item|
			sum += item.price
		end
		return sum
	end

	def not_empty?
		if @current_cart.items.length != 0
			true
		else
			false
		end
	end
end

app/views/carts/show.html.erb
<div class="col-md-12"> 
	<div class="card card-plain">
		<div class="card-body">
			<div class="table-responsive">
				<table class="table table-shopping">
					<thead class="">
						<tr><th class="text-center"></th>
							<th>Produit</th>
							<th>Description</th>
							<th class="text-right">Prix</th>
						</tr>
					</thead>
					<tbody>
						<% @cart.join_table_cart_items.each do |cart_item| %>
						<tr>
							<td>
							<div class="img-container">
							<%= image_tag(cart_item.item.image) %>
							</div>
							</td>
							<td class="td-name"><%= cart_item.item.title %></td>
							<td class="td-name"><%= cart_item.item.description %></td>
							<td class="td-number"><%= cart_item.item.price %><small>€</small></td>
							<td class="td-actions">
							<!--<button type="button" rel="tooltip" data-placement="left" title="" class="btn btn-neutral" data-original-title="Remove item">
							<i class="fas fa-times"></i>
							</button>-->
							<%= button_to "X", item_join_table_cart_item_path(item_id: cart_item.item, id: cart_item), {method: :delete, :class => "btn btn-neutral"} %>
							</td>
						</tr>
						<% end %>
						<tr>
							<td colspan="2"></td>
							<td class="td-total">Total</td>
							<td class="td-price"><small>€</small><%= @sum %></td>
							<td colspan="3" class="text-right">

							<!-- BOUTON DE PURCHASAGE -->
							 <% if @sum > 0 %>
								<%= form_tag charges_path do %> 
									<input type="text" name="cart_amount" value="<%= (@sum * 100).round %>" hidden>   

									<script  
										src="https://checkout.stripe.com/checkout.js" class="stripe-button" 
										data-key="<%= ENV['PUBLISHABLE_KEY'] %>"    
										data-amount="<%= @sum * 100 %>"   
										data-name="Demo Site"   
										data-description="Example charge"   
										data-image="https://stripe.com/img/documentation/checkout/marketplace.png"  
										data-locale="auto"  
										data-currency="eur">    
									</script> 


									<% end %>
								<% end %>
							</td>
						</tr>
					</tbody>
				</table>
				<%= button_to "Continuer les achats", root_path, {method: :get, :class => "btn btn-neutral"} %>
			</div>
		</div>
	</div>
</div>
<% if not_empty? %>
	<div class="main">
    <div class="section" id='img-ancre'>
      <div class="container">
        <h2 class="section-title">Vous aimez vos photos de chatounes ? Offrez-leur une photo de croquette !</h2>
        <div class="col-md-12">
          <div class="row">
            <% @items.each do |item| %>
            <% if is_kibble?(item) %>
              <div class="col-lg-4 col-md-6">
                <div class="card-index">
                  <div>
                    <%= link_to image_tag(item.image), item_join_table_cart_items_path(item), method: :post, remote: true %>
                  </div>
                  <div class="card-body">
                    <% if @current_cart.items.find_by_id(item.id) %>
                      <h4 class="title-card"><%= item.title %> <i class="fas fa-shopping-cart fa-xs"></i></h4>
                    <% else %>
                      <h4 class="title-card"><%= item.title %></h4>
                    <% end %>
                    <p class="description-card">
                      <%= item.description %>
                    </p>
                    <div class="price-container">
                      <span class="price"> &euro; <%= item.price %></span>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>