config/routes.rb
Rails.application.routes.draw do

	root 'items#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users

  resources :items do
    resources :join_table_cart_items
  end

  resources :carts, param: :permalink
  # match 'my_cart', to: 'carts#show', via: [:get]
  resources :orders
  resources :charges, only: [:new, :create]

  namespace :admin do
    resources :items
    resources :admins, only: [:index]
    root 'admins#index'
  end

  # get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
	# VALIDATES
	validates :title, presence: true
	validates :description, presence: true, length: { in: 5..100 }
	validates :price, presence: true, numericality: { greater_than: 0 }
	validates :image, presence: true

	has_many :join_table_cart_items
	has_many :carts, through: :join_table_cart_items

	has_many :order_items
	has_many :orders, through: :order_items

	has_one_attached :image

	belongs_to :category
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :is_admin?

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    if params[:item][:image].present?
      @item = Item.new(item_params)
      @item.image_url = url_for(@item.image)
      @item.image.attach(params[:item][:image])
      if @item.save
        redirect_to admin_item_path(@item.id)
      else
        render :new
      end
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path, notice: "L'item a bien été supprimé."
  end


  private
  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :description, :price, :image, :category_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :is_admin?, only: [:destroy, :update, :edit]


  def index
    @items = Item.all
  end

 
  def show
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url)
    end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
	def is_kitty?(item)
		if item.category == Category.first
			true
		else
			false
		end
	end

	def is_kibble?(item)
		if item.category == Category.last
			true
		else
			false
		end
	end
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="ecommerce-page">
  <div class="wrapper">
    <div class="banner">
      <div class='img-banner'>
        <%= image_tag("banner.jpg") %>
      </div>
      <div class='text-banner'>
        <h3 class='txt-ban-prim'>Fan de chatoune ?</h3>
        <h5 class='txt-ban-sec'>Viens regarder les différentes images que nous proposons !</h5>
      </br>
      <button class='btn btn-secondary' id='btn-banner' onclick="slideIndex();">Nos images disponibles</button>
    </div>
  </div>
  <div class="main">
    <div class="section" id='img-ancre'>
      <div class="container">
        <h2 class="section-title">Toutes nos images disponibles</h2>
        <div class="col-md-12">
          <div class="row">
            <% @items.each do |item| %>
            <% if is_kitty?(item) %>
              <div class="col-lg-4 col-md-6">
                <div class="card-index">
                  <div>
                    <%= link_to item_path(item.id) do %>
                      <%= image_tag(item.image) if item.image.attached? %>
                    <% end %>
                  </div>
                  <div class="card-body">
                    <% if @current_cart.items.find_by_id(item.id) %>
                      <h4 class="title-card"><%= item.title %> <i class="fas fa-shopping-cart fa-xs"></i></h4>
                    <% else %>
                      <h4 class="title-card"><%= item.title %></h4>
                    <% end %>
                    <p class="description-card">
                      <%= item.description %>
                    </p>
                    <div class="price-container">
                      <span class="price"> &euro; <%= item.price %></span>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<div class="container">

  <div class="row">
  	<div class="col mt-2">
  		<h2 class="title"><%= @item.title %></h2>
			<p id="notice"><%= notice %></p>
  	</div>
  </div>
	
	<div class="row mb-3">
		<div class="col-md-5 mr-auto">
	  	 	<%= image_tag(@item.image) if @item.image.attached? %>
		</div>

		<div class="col-md-7">
			<h5 class="category">Description</h5>
			<p><%= @item.description %></p>
		</div>
	</div>
	
	<div class="row align-items-center ">


		<div class="col-md-2 ml-auto text-center">
			<span class="title"><%= @item.price %> €</span>
		</div>

		<div class="col-md-2">
			<% if logged_in? %>

				<% if !@current_cart.items.find_by_id(@item.id) %>
					<%= button_to "Add to cart", item_join_table_cart_items_path(@item.id), {method: :post, :class => "btn btn-lg btn-primary"} %>
				<% else %>
					<%= button_to "Already in the cart", item_join_table_cart_items_path(@item.id), {method: :post, :class => "btn btn-lg btn-primary", :disabled => true} %>
				<% end %>

				<%= button_to "Voir mon panier", cart_path(@current_cart), {method: :get, :class => "btn btn-lg btn-primary"} %>
			<% end %>
		</div>
	</div>

	<div class="row mt-5">
		<div class="col-md text-right">
			<%= link_to 'Back', items_path %>
		</div>
	</div>

</div>
 