config/routes.rb
Rails.application.routes.draw do

	root 'items#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users

  resources :items do
    resources :join_table_cart_items
  end

  resources :carts, param: :permalink
  # match 'my_cart', to: 'carts#show', via: [:get]
  resources :orders
  resources :charges, only: [:new, :create]

  namespace :admin do
    resources :items
    resources :admins, only: [:index]
    root 'admins#index'
  end

  # get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	
	has_many :join_table_cart_items
	has_many :items, through: :join_table_cart_items
	#has_many :good_orders

	def to_param
		permalink
	end

  def permalink
  	"my_cart"
	end

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
	# VALIDATES
	validates :title, presence: true
	validates :description, presence: true, length: { in: 5..100 }
	validates :price, presence: true, numericality: { greater_than: 0 }
	validates :image, presence: true

	has_many :join_table_cart_items
	has_many :carts, through: :join_table_cart_items

	has_many :order_items
	has_many :orders, through: :order_items

	has_one_attached :image

	belongs_to :category
end

app/models/join_table_cart_item.rb
class JoinTableCartItem < ApplicationRecord
	belongs_to :cart
	belongs_to :item
end

app/models/order.rb
class Order < ApplicationRecord

	belongs_to :user
	#belongs_to :cart
	has_many :order_items
	has_many :items, through: :order_items

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart
  has_many :orders

   validates :first_name, presence: true
   validates :last_name, presence: true

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :authenticate_user!, only: [:show]

	def show
		@cart = @current_cart
		@sum = sum(@cart)
		@items = Item.all
	end

	def destroy
		@cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :is_admin?, only: [:destroy, :update, :edit]


  def index
    @items = Item.all
  end

 
  def show
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if current_user.id.to_i != params[:id].to_i
      redirect_to root_path
    else
    @my_orders = @user.orders
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if current_user.id.to_i == params[:id].to_i
        @user = User.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def bootstrap_class_for_flash(type)
	  case type
	    when 'notice' then "alert-info"
	    when 'success' then "alert-success"
	    when 'error' then "alert-danger"
	    when 'alert' then "alert-warning"
	  end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
	def sum(cart)
		sum = 0
		cart.items.each do |item|
			sum += item.price
		end
		return sum
	end

	def not_empty?
		if @current_cart.items.length != 0
			true
		else
			false
		end
	end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
end

app/helpers/good_orders_helper.rb
module GoodOrdersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
	def is_kitty?(item)
		if item.category == Category.first
			true
		else
			false
		end
	end

	def is_kibble?(item)
		if item.category == Category.last
			true
		else
			false
		end
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
	def sum_order(order)
		sum = 0
		order.order_items.each do |item|
			sum += item.item.price
		end
		return sum
	end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def logged_in?
  		if !current_user.nil?
  			true
  		else
  			false
  		end
	end

	def is_admin?
		unless !current_user.nil? && current_user.is_admin?
		  flash[:danger] = "Il semble que tu n'es pas administrateur du site, tu ne peux pas accéder à cette page."
		  redirect_back(fallback_location: root_path)
		end
	end

	def admin_navbar?
		if !current_user.nil? && current_user.is_admin?
			true
		else
			false
		end
	end
end

app/views/admin/admins/index.html.erb
<div class="banner">
            <div class='img-banner'>
                <%= image_tag("banner.jpg") %>
            </div>
            <div class='text-banner'>
                <h3 class='txt-ban-prim'>Bonjour <%= current_user.first_name %> !</h3>
                <h5 class='txt-ban-sec'>Bienvenue dans le dashboard admin</h5>
            </div>
        </div> 

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show mb-0" role="alert">
    <%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 footer footer-default">
  <div class="container">
    <nav>
      <ul>
        <li><a href="#creative">Miaouu!</a></li>
      </ul>
    </nav>
    <div class="copyright">
      &copy;2019, Designed and Coded by Mister Fantastic, Invisible Woman, Human Torch and Thing.
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-white float-top mb-0">
      <div class="container">
        <div class="navbar-translate">
          <a class="navbar-brand" href="<%= root_path %>" rel="tooltip" title="Designed and Coded by fantastic four" data-placement="bottom">
            Plus de chatounes
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar bar1"></span>
            <span class="navbar-toggler-bar bar2"></span>
            <span class="navbar-toggler-bar bar3"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" data-nav-image="../assets/img/blurred-image-1.jpg" data-color="orange">
        
          <div class="navbar-nav flex-row ml-md-auto d-none d-md-flex">    
            <% if user_signed_in? %>
              <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <% if current_user.first_name != nil %>
                  <%= current_user.first_name %>
                <% end %>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <%= link_to user_path(current_user.id), :class => "dropdown-item" do %>
                  <i class="fas fa-user-circle"></i> My Profile
                  <% end %>
                  <%= link_to destroy_user_session_path, method: :delete,  data: { confirm: "Tu es sûr-e ?" }, :class => "dropdown-item" do %>
                  <i class="fas fa-sign-out-alt"></i> Log out
                  <% end %>
                </div>
              </div>
            <% else %>
              <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Connexion
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <%= link_to new_user_session_path, :class => "dropdown-item" do %>
                  <i class="fas fa-sign-in-alt"></i> Log in
                  <% end %>
                  <%= link_to new_user_registration_path, :class => "dropdown-item" do %>
                  <i class="fas fa-user-plus"></i> Sign up
                  <% end %>
                </div>
              </div>
            <% end %>
            <% if user_signed_in? %>
            <div class="nav-item align-self-center">
              <a href="<%= cart_path(current_user.cart) %>"><i class="fas fa-shopping-cart"></i> Cart</a>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </nav>

app/views/layouts/_navbar_admin.html.erb
<nav class="navbar navbar-expand-lg bg-white float-top mb-0">
      <div class="container">
        <div class="navbar-translate">
          <a class="navbar-brand" href="<%= admin_root_path %>" rel="tooltip" title="Designed and Coded by fantastic four" data-placement="bottom">
            Plus de chatounes | Dashboard admin
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar bar1"></span>
            <span class="navbar-toggler-bar bar2"></span>
            <span class="navbar-toggler-bar bar3"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Gérer les items
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                    <%= link_to admin_items_path, :class => "dropdown-item" do %>
                    Voir tous les items
                    <% end %>
                    <%= link_to new_admin_item_path, :class => "dropdown-item" do %>
                    Ajouter un item
                    <% end %>
                </div>
              </div>
        </div>
                </li>
            </ul>
        </div>
        <div class="collapse navbar-collapse" data-nav-image="../assets/img/blurred-image-1.jpg" data-color="orange">
        
          <div class="navbar-nav flex-row ml-md-auto d-none d-md-flex">    
              <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <% if current_user.first_name != nil %>
                  <%= current_user.first_name %>
                <% end %>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <%= link_to user_path(current_user.id), :class => "dropdown-item" do %>
                  <i class="fas fa-user-circle"></i> My Profile
                  <% end %>
                  <%= link_to destroy_user_session_path, method: :delete,  data: { confirm: "Tu es sûr-e ?" }, :class => "dropdown-item" do %>
                  <i class="fas fa-sign-out-alt"></i> Log out
                  <% end %>
                </div>
              </div>
          </div>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlusDeChatounes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="landing-page  d-flex flex-column">

    <% if admin_navbar? %>
      <%= render 'layouts/navbar_admin' %>
    <% else %>
      <%= render 'layouts/navbar' %>
    <% end %>
 

    <%= render 'layouts/flash'%>

    <div id="page-content">
      <%= yield %>
    </div>

    <% current_uri = request.env['PATH_INFO'] %>
    <% if current_uri != "/users/sign_up" && current_uri != "/users/sign_in"  %>
      <%= render "/layouts/footer" %>
    <% end %>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>